#component_name=user
#source common.sh
#
#  #cp user.service /etc/systemd/system/user.service
#
#nodejs
#
#systemd_setup

- name: Run NodeJS
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs



- name: Run systemd_setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd_setup
