#if [ -z "${MYSQL_ROOT_PASSWORD}" -a -z "$1" ]; then
#echo Input password is missing
#exit 1
#fi
#
#if [ -n "${MYSQL_ROOT_PASSWORD}" ]; then
#PASSWORD=$MYSQL_ROOT_PASSWORD
#fi
#
#if [ -n "$1" ]; then
#PASSWORD=$1
#fi
#
#dnf install mysql-server -y
#systemctl enable mysqld
#systemctl start mysqld
#
#mysql_secure_installation --set-root-pass $PASSWORD
#
##RoboShop@1

- name: Install MySQL Server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: Start MySQLD
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: yes

- name: Setup MySQL Root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1