#id roboshop || useradd roboshop
#rm -rf /app
#mkdir /app
#cd /app
#  #  npm install
#curl -L -o /tmp/${component_name}.zip https://roboshop-artifacts.s3.amazonaws.com/${component_name}-v3.zip
#cd /app
##unzip /tmp/${component_name}.zip

- name: Add application user
  ansible.builtin.user:
    name: roboshop

- name: Delete old App directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ app_name }}-v3.zip
    dest: /app
    remote_src: yes