#dnf install maven -y
#app_pre_setup
#
#mvn clean package
#mv target/${component_name}-1.0.jar ${component_name}.jar

- name: Install Maven
  ansible.builtin.dnf:
    name: maven
    state: present

- name: Load App Pre-requisites
  ansible.builtin.include_tasks:
    file: app_pre_setup.yaml

- name: Download App Dependencies
  ansible.builtin.shell: mvn clean package ;  mv target/{{ app_name }}-1.0.jar {{ app_name }}.jar
  args:
    chdir: /app

