#dnf install python3 gcc python3-devel -y
##  cp payment.service /etc/systemd/system/payment.service
#app_pre_setup
#
#pip3 install -r requirements.txt

- name: Install Python
  ansible.builtin.dnf:
    name:
      - python3
      - gcc
      - python3-devel
    state: present

- name: Load App Pre-requisites
  ansible.builtin.include_tasks:
    file: app_pre_setup.yaml

- name: Download App Dependencies
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /app